# Generated by Django 2.0.8 on 2019-10-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='deleted_at',
        ),
    ]
