# Generated by Django 2.0.8 on 2019-10-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='url',
        ),
    ]
